### ISSUE TITLE
[FEATURE]: parse the serialize_credentials() to get an object

### ISSUE THREAD

**Issue by FlavioAandres** [AndresMorelos/manage-aws-credentials#21]
we can read the `~/.aws/configure` file and parse it to an object like: 

```
{
 profiles: [{
  name:'profilename', 
  accessKey: 'abc',
  secretKey: 'abc'
 }]
}
```

**Comment by FlavioAandres** [comment]
@AndresMorelos Hey i just checked the code and i foudn that you've currently this information as object in your code, the only one thing to do is return it as object instead of a string. 

What do you think?

**Comment by AndresMorelos** [comment]
@FlavioAandres using the method `get_credentials` you're will be able to get an object of the profiles.

Is the object returned by this method valid for you or do you need it on the schema specified on the first comment?

**Comment by AndresMorelos** [comment]
hey @FlavioAandres I've implemented a format param on the method `serialize_credentials` to get the data serialized as `text` or `object`

Format Params Accepted Vales are: `text, object`, by default, is text.
